### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thomasnonis** [eagletrt/an2can#1]
## Schematic
- [x] Add temperature sensor
- [x] Consider not using too many rnets to allow better per-channel configurability
- [x] Change to STM32L432KCU
- [x] Research instramp vs differential opamp
- [x] Verify actual oscillator PN with lab stock
- [x] Check oscillator footprint
- [x] Check availability of temperature sensors in lab
- [x] Add optional resistor for opamp gain
- [x] Consider adding BAT54S
- [x] INAs might not work with single supply
- [x] Define supply structure/TexDCDC
- [x] Share input pulls with bridges. Start with this, only after first PCB draft consider sharing footprints
- [x] Check that we have 02x08 connectors
- [x] Verify connector symbols numbering order
- [x] MCU PAD GND is currently connected do GNDA, introducing enormous loops. Connect to GND. Probably the best solution is to place the net tie at the MCU.
There is no VSSA pin on this package
- [x] Substitute schottky clamps with BAT or arrays at MCU
- [x] Add mounting holes/holes for zip-ties
- [x] Consider that board should actually power the sensors
- [x] Add additional LDO to 5V rail and consider using LDOs instead of FBs to create adc pwr
- [x] Add input series resistor to make input voltage divider
- [x] Add 3v3 analog reading
- [x] Add FB to usb
- [ ] Add SOD-323 alternative to schottkys

## PCB
- [x] Remember to keep analog and digital section separate
- [x] Use elongated pads in QFN footprint
- [ ] Do not tent vias
- [x] Connect GND and GNDA at mcu, since there is no separation in it
- [x] Clock is close to VDDA pin, isolate as much as possible
- [x] Create custom smaller footprints for solder jumpers or use 0R
- [x] Add many VIAs, especially under DCDC
- [ ] Remember teardrops
- [x] Remember that +5VA are not routed between connectors currently

**Comment by thomasnonis** [comment]
Available OSC: DSC6101C2A (many) and DSC1001CC1-008.0000 (few)
Available NTC: ERT-J1VV104J, PCT2075TP,147
2x08 connectors not needed anymore, in any case we do have them

**Comment by thomasnonis** [comment]
Output of TexDCDC has ~40mV of ripple, LSB is ~800uV

**Comment by thomasnonis** [comment]
Largest zip-tie is 1.9 x 4.3mm
